elasticsearch:
  image: elasticsearch:latest
  ports:
    - "9200:9200"
    - "9300:9300"
  volumes:
    - "./elasticsearch.yml:/opt/elasticsearch/config/elasticsearch.yml"
  command: elasticsearch -Des.network.host=0.0.0.0

redis:
  image: redis:3.0.0
  ports:
    - "6379:6379"

logstash:
  image: logstash:latest
  ports:
    - "5000:5000"
    - "5000:5000/udp"
  links:
    - redis
    - elasticsearch
  volumes:
    - "./logstash.conf:/etc/logstash.conf"
  command: -f /etc/logstash.conf

kibana:
  image: kibana:latest
  links:
    - elasticsearch
  ports:
    - "80:80"
    - "5601:5601"